# Generated by Django 5.2.1 on 2025-05-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight_hub', '0004_dashboard_allowed_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='y_column',
            field=models.CharField(default='default_y_column', max_length=100, null=True),
        ),
    ]
