# Generated by Django 5.2.1 on 2025-05-19 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight_hub', '0005_alter_chart_y_column'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csvfile',
            name='dashboard',
        ),
        migrations.AddField(
            model_name='csvfile',
            name='chart',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='csv_file', to='insight_hub.chart'),
            preserve_default=False,
        ),
    ]
