# Generated by Django 5.2.1 on 2025-05-19 20:32

import insight_hub.models.CSVfile
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight_hub', '0006_remove_csvfile_dashboard_csvfile_chart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfile',
            name='file_path',
            field=models.FileField(upload_to=insight_hub.models.CSVfile.unique_csv_file_path),
        ),
    ]
