# Generated by Django 5.2.1 on 2025-05-20 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight_hub', '0007_alter_csvfile_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='y_column',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
