# Generated by Django 5.2.1 on 2025-05-20 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight_hub', '0008_alter_chart_y_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='chart_type',
            field=models.CharField(choices=[('line', 'LineChart'), ('bar', 'BarChart'), ('pie', 'PieChart')], default='line', max_length=10),
        ),
    ]
