# Generated by Django 5.2.1 on 2025-05-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight_hub', '0009_alter_chart_chart_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='operation',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
