# Generated by Django 5.2.1 on 2025-05-20 15:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight_hub', '0010_chart_operation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='dashboard_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
